/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as DashboardLayoutRouteImport } from './app/dashboard/layout'
import { Route as nondashboardLayoutRouteImport } from './app/(nondashboard)/layout'
import { Route as authLayoutRouteImport } from './app/(auth)/layout'
import { Route as PageRouteImport } from './app/page'
import { Route as nondashboardMapRouteImport } from './app/(nondashboard)/map'
import { Route as nondashboardLandingRouteImport } from './app/(nondashboard)/landing'
import { Route as DashboardTenantLayoutRouteImport } from './app/dashboard/tenant/layout'
import { Route as DashboardManagerLayoutRouteImport } from './app/dashboard/manager/layout'
import { Route as authRegisterTenantRouteImport } from './app/(auth)/register/tenant'
import { Route as authRegisterManagerRouteImport } from './app/(auth)/register/manager'
import { Route as authLoginTenantRouteImport } from './app/(auth)/login/tenant'
import { Route as authLoginManagerRouteImport } from './app/(auth)/login/manager'
import { Route as DashboardTenantsectionsPageRouteImport } from './app/dashboard/tenant/(sections)/page'
import { Route as DashboardManagersectionsPageRouteImport } from './app/dashboard/manager/(sections)/page'
import { Route as DashboardTenantsectionsSettingsRouteImport } from './app/dashboard/tenant/(sections)/settings'
import { Route as DashboardManagersectionsCreatePropertyRouteImport } from './app/dashboard/manager/(sections)/create-property'
import { Route as DashboardTenantsectionsResidencesPageRouteImport } from './app/dashboard/tenant/(sections)/residences/page'
import { Route as DashboardTenantsectionsFavouritesPageRouteImport } from './app/dashboard/tenant/(sections)/favourites/page'
import { Route as DashboardTenantsectionsApplicationsPageRouteImport } from './app/dashboard/tenant/(sections)/applications/page'
import { Route as DashboardManagersectionsManagedPropertiesPageRouteImport } from './app/dashboard/manager/(sections)/managed-properties/page'
import { Route as DashboardTenantsectionsResidencesIdRouteImport } from './app/dashboard/tenant/(sections)/residences/$id'
import { Route as DashboardTenantsectionsFavouritesIdRouteImport } from './app/dashboard/tenant/(sections)/favourites/$id'
import { Route as DashboardTenantsectionsApplicationsIdRouteImport } from './app/dashboard/tenant/(sections)/applications/$id'
import { Route as DashboardManagersectionsManagedPropertiesIdRouteImport } from './app/dashboard/manager/(sections)/managed-properties/$id'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const nondashboardLayoutRoute = nondashboardLayoutRouteImport.update({
  id: '/(nondashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const nondashboardMapRoute = nondashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => nondashboardLayoutRoute,
} as any)
const nondashboardLandingRoute = nondashboardLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => nondashboardLayoutRoute,
} as any)
const DashboardTenantLayoutRoute = DashboardTenantLayoutRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardManagerLayoutRoute = DashboardManagerLayoutRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const authRegisterTenantRoute = authRegisterTenantRouteImport.update({
  id: '/register/tenant',
  path: '/register/tenant',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterManagerRoute = authRegisterManagerRouteImport.update({
  id: '/register/manager',
  path: '/register/manager',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginTenantRoute = authLoginTenantRouteImport.update({
  id: '/login/tenant',
  path: '/login/tenant',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginManagerRoute = authLoginManagerRouteImport.update({
  id: '/login/manager',
  path: '/login/manager',
  getParentRoute: () => authLayoutRoute,
} as any)
const DashboardTenantsectionsPageRoute =
  DashboardTenantsectionsPageRouteImport.update({
    id: '/(sections)/',
    path: '/',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardManagersectionsPageRoute =
  DashboardManagersectionsPageRouteImport.update({
    id: '/(sections)/',
    path: '/',
    getParentRoute: () => DashboardManagerLayoutRoute,
  } as any)
const DashboardTenantsectionsSettingsRoute =
  DashboardTenantsectionsSettingsRouteImport.update({
    id: '/(sections)/settings',
    path: '/settings',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardManagersectionsCreatePropertyRoute =
  DashboardManagersectionsCreatePropertyRouteImport.update({
    id: '/(sections)/create-property',
    path: '/create-property',
    getParentRoute: () => DashboardManagerLayoutRoute,
  } as any)
const DashboardTenantsectionsResidencesPageRoute =
  DashboardTenantsectionsResidencesPageRouteImport.update({
    id: '/(sections)/residences/',
    path: '/residences/',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardTenantsectionsFavouritesPageRoute =
  DashboardTenantsectionsFavouritesPageRouteImport.update({
    id: '/(sections)/favourites/',
    path: '/favourites/',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardTenantsectionsApplicationsPageRoute =
  DashboardTenantsectionsApplicationsPageRouteImport.update({
    id: '/(sections)/applications/',
    path: '/applications/',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardManagersectionsManagedPropertiesPageRoute =
  DashboardManagersectionsManagedPropertiesPageRouteImport.update({
    id: '/(sections)/managed-properties/',
    path: '/managed-properties/',
    getParentRoute: () => DashboardManagerLayoutRoute,
  } as any)
const DashboardTenantsectionsResidencesIdRoute =
  DashboardTenantsectionsResidencesIdRouteImport.update({
    id: '/(sections)/residences/$id',
    path: '/residences/$id',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardTenantsectionsFavouritesIdRoute =
  DashboardTenantsectionsFavouritesIdRouteImport.update({
    id: '/(sections)/favourites/$id',
    path: '/favourites/$id',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardTenantsectionsApplicationsIdRoute =
  DashboardTenantsectionsApplicationsIdRouteImport.update({
    id: '/(sections)/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => DashboardTenantLayoutRoute,
  } as any)
const DashboardManagersectionsManagedPropertiesIdRoute =
  DashboardManagersectionsManagedPropertiesIdRouteImport.update({
    id: '/(sections)/managed-properties/$id',
    path: '/managed-properties/$id',
    getParentRoute: () => DashboardManagerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof nondashboardLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/manager': typeof DashboardManagerLayoutRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantLayoutRouteWithChildren
  '/landing': typeof nondashboardLandingRoute
  '/map': typeof nondashboardMapRoute
  '/login/manager': typeof authLoginManagerRoute
  '/login/tenant': typeof authLoginTenantRoute
  '/register/manager': typeof authRegisterManagerRoute
  '/register/tenant': typeof authRegisterTenantRoute
  '/dashboard/manager/create-property': typeof DashboardManagersectionsCreatePropertyRoute
  '/dashboard/tenant/settings': typeof DashboardTenantsectionsSettingsRoute
  '/dashboard/manager/': typeof DashboardManagersectionsPageRoute
  '/dashboard/tenant/': typeof DashboardTenantsectionsPageRoute
  '/dashboard/manager/managed-properties/$id': typeof DashboardManagersectionsManagedPropertiesIdRoute
  '/dashboard/tenant/applications/$id': typeof DashboardTenantsectionsApplicationsIdRoute
  '/dashboard/tenant/favourites/$id': typeof DashboardTenantsectionsFavouritesIdRoute
  '/dashboard/tenant/residences/$id': typeof DashboardTenantsectionsResidencesIdRoute
  '/dashboard/manager/managed-properties': typeof DashboardManagersectionsManagedPropertiesPageRoute
  '/dashboard/tenant/applications': typeof DashboardTenantsectionsApplicationsPageRoute
  '/dashboard/tenant/favourites': typeof DashboardTenantsectionsFavouritesPageRoute
  '/dashboard/tenant/residences': typeof DashboardTenantsectionsResidencesPageRoute
}
export interface FileRoutesByTo {
  '/': typeof nondashboardLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/landing': typeof nondashboardLandingRoute
  '/map': typeof nondashboardMapRoute
  '/login/manager': typeof authLoginManagerRoute
  '/login/tenant': typeof authLoginTenantRoute
  '/register/manager': typeof authRegisterManagerRoute
  '/register/tenant': typeof authRegisterTenantRoute
  '/dashboard/manager/create-property': typeof DashboardManagersectionsCreatePropertyRoute
  '/dashboard/tenant/settings': typeof DashboardTenantsectionsSettingsRoute
  '/dashboard/manager': typeof DashboardManagersectionsPageRoute
  '/dashboard/tenant': typeof DashboardTenantsectionsPageRoute
  '/dashboard/manager/managed-properties/$id': typeof DashboardManagersectionsManagedPropertiesIdRoute
  '/dashboard/tenant/applications/$id': typeof DashboardTenantsectionsApplicationsIdRoute
  '/dashboard/tenant/favourites/$id': typeof DashboardTenantsectionsFavouritesIdRoute
  '/dashboard/tenant/residences/$id': typeof DashboardTenantsectionsResidencesIdRoute
  '/dashboard/manager/managed-properties': typeof DashboardManagersectionsManagedPropertiesPageRoute
  '/dashboard/tenant/applications': typeof DashboardTenantsectionsApplicationsPageRoute
  '/dashboard/tenant/favourites': typeof DashboardTenantsectionsFavouritesPageRoute
  '/dashboard/tenant/residences': typeof DashboardTenantsectionsResidencesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(nondashboard)': typeof nondashboardLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/manager': typeof DashboardManagerLayoutRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantLayoutRouteWithChildren
  '/(nondashboard)/landing': typeof nondashboardLandingRoute
  '/(nondashboard)/map': typeof nondashboardMapRoute
  '/(auth)/login/manager': typeof authLoginManagerRoute
  '/(auth)/login/tenant': typeof authLoginTenantRoute
  '/(auth)/register/manager': typeof authRegisterManagerRoute
  '/(auth)/register/tenant': typeof authRegisterTenantRoute
  '/dashboard/manager/(sections)/create-property': typeof DashboardManagersectionsCreatePropertyRoute
  '/dashboard/tenant/(sections)/settings': typeof DashboardTenantsectionsSettingsRoute
  '/dashboard/manager/(sections)/': typeof DashboardManagersectionsPageRoute
  '/dashboard/tenant/(sections)/': typeof DashboardTenantsectionsPageRoute
  '/dashboard/manager/(sections)/managed-properties/$id': typeof DashboardManagersectionsManagedPropertiesIdRoute
  '/dashboard/tenant/(sections)/applications/$id': typeof DashboardTenantsectionsApplicationsIdRoute
  '/dashboard/tenant/(sections)/favourites/$id': typeof DashboardTenantsectionsFavouritesIdRoute
  '/dashboard/tenant/(sections)/residences/$id': typeof DashboardTenantsectionsResidencesIdRoute
  '/dashboard/manager/(sections)/managed-properties/': typeof DashboardManagersectionsManagedPropertiesPageRoute
  '/dashboard/tenant/(sections)/applications/': typeof DashboardTenantsectionsApplicationsPageRoute
  '/dashboard/tenant/(sections)/favourites/': typeof DashboardTenantsectionsFavouritesPageRoute
  '/dashboard/tenant/(sections)/residences/': typeof DashboardTenantsectionsResidencesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/manager'
    | '/dashboard/tenant'
    | '/landing'
    | '/map'
    | '/login/manager'
    | '/login/tenant'
    | '/register/manager'
    | '/register/tenant'
    | '/dashboard/manager/create-property'
    | '/dashboard/tenant/settings'
    | '/dashboard/manager/'
    | '/dashboard/tenant/'
    | '/dashboard/manager/managed-properties/$id'
    | '/dashboard/tenant/applications/$id'
    | '/dashboard/tenant/favourites/$id'
    | '/dashboard/tenant/residences/$id'
    | '/dashboard/manager/managed-properties'
    | '/dashboard/tenant/applications'
    | '/dashboard/tenant/favourites'
    | '/dashboard/tenant/residences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/map'
    | '/login/manager'
    | '/login/tenant'
    | '/register/manager'
    | '/register/tenant'
    | '/dashboard/manager/create-property'
    | '/dashboard/tenant/settings'
    | '/dashboard/manager'
    | '/dashboard/tenant'
    | '/dashboard/manager/managed-properties/$id'
    | '/dashboard/tenant/applications/$id'
    | '/dashboard/tenant/favourites/$id'
    | '/dashboard/tenant/residences/$id'
    | '/dashboard/manager/managed-properties'
    | '/dashboard/tenant/applications'
    | '/dashboard/tenant/favourites'
    | '/dashboard/tenant/residences'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(nondashboard)'
    | '/dashboard'
    | '/dashboard/manager'
    | '/dashboard/tenant'
    | '/(nondashboard)/landing'
    | '/(nondashboard)/map'
    | '/(auth)/login/manager'
    | '/(auth)/login/tenant'
    | '/(auth)/register/manager'
    | '/(auth)/register/tenant'
    | '/dashboard/manager/(sections)/create-property'
    | '/dashboard/tenant/(sections)/settings'
    | '/dashboard/manager/(sections)/'
    | '/dashboard/tenant/(sections)/'
    | '/dashboard/manager/(sections)/managed-properties/$id'
    | '/dashboard/tenant/(sections)/applications/$id'
    | '/dashboard/tenant/(sections)/favourites/$id'
    | '/dashboard/tenant/(sections)/residences/$id'
    | '/dashboard/manager/(sections)/managed-properties/'
    | '/dashboard/tenant/(sections)/applications/'
    | '/dashboard/tenant/(sections)/favourites/'
    | '/dashboard/tenant/(sections)/residences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  nondashboardLayoutRoute: typeof nondashboardLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nondashboard)': {
      id: '/(nondashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof nondashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nondashboard)/map': {
      id: '/(nondashboard)/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof nondashboardMapRouteImport
      parentRoute: typeof nondashboardLayoutRoute
    }
    '/(nondashboard)/landing': {
      id: '/(nondashboard)/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof nondashboardLandingRouteImport
      parentRoute: typeof nondashboardLayoutRoute
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/(auth)/register/tenant': {
      id: '/(auth)/register/tenant'
      path: '/register/tenant'
      fullPath: '/register/tenant'
      preLoaderRoute: typeof authRegisterTenantRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register/manager': {
      id: '/(auth)/register/manager'
      path: '/register/manager'
      fullPath: '/register/manager'
      preLoaderRoute: typeof authRegisterManagerRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login/tenant': {
      id: '/(auth)/login/tenant'
      path: '/login/tenant'
      fullPath: '/login/tenant'
      preLoaderRoute: typeof authLoginTenantRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login/manager': {
      id: '/(auth)/login/manager'
      path: '/login/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof authLoginManagerRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/dashboard/tenant/(sections)/': {
      id: '/dashboard/tenant/(sections)/'
      path: '/'
      fullPath: '/dashboard/tenant/'
      preLoaderRoute: typeof DashboardTenantsectionsPageRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/manager/(sections)/': {
      id: '/dashboard/manager/(sections)/'
      path: '/'
      fullPath: '/dashboard/manager/'
      preLoaderRoute: typeof DashboardManagersectionsPageRouteImport
      parentRoute: typeof DashboardManagerLayoutRoute
    }
    '/dashboard/tenant/(sections)/settings': {
      id: '/dashboard/tenant/(sections)/settings'
      path: '/settings'
      fullPath: '/dashboard/tenant/settings'
      preLoaderRoute: typeof DashboardTenantsectionsSettingsRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/manager/(sections)/create-property': {
      id: '/dashboard/manager/(sections)/create-property'
      path: '/create-property'
      fullPath: '/dashboard/manager/create-property'
      preLoaderRoute: typeof DashboardManagersectionsCreatePropertyRouteImport
      parentRoute: typeof DashboardManagerLayoutRoute
    }
    '/dashboard/tenant/(sections)/residences/': {
      id: '/dashboard/tenant/(sections)/residences/'
      path: '/residences'
      fullPath: '/dashboard/tenant/residences'
      preLoaderRoute: typeof DashboardTenantsectionsResidencesPageRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/tenant/(sections)/favourites/': {
      id: '/dashboard/tenant/(sections)/favourites/'
      path: '/favourites'
      fullPath: '/dashboard/tenant/favourites'
      preLoaderRoute: typeof DashboardTenantsectionsFavouritesPageRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/tenant/(sections)/applications/': {
      id: '/dashboard/tenant/(sections)/applications/'
      path: '/applications'
      fullPath: '/dashboard/tenant/applications'
      preLoaderRoute: typeof DashboardTenantsectionsApplicationsPageRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/manager/(sections)/managed-properties/': {
      id: '/dashboard/manager/(sections)/managed-properties/'
      path: '/managed-properties'
      fullPath: '/dashboard/manager/managed-properties'
      preLoaderRoute: typeof DashboardManagersectionsManagedPropertiesPageRouteImport
      parentRoute: typeof DashboardManagerLayoutRoute
    }
    '/dashboard/tenant/(sections)/residences/$id': {
      id: '/dashboard/tenant/(sections)/residences/$id'
      path: '/residences/$id'
      fullPath: '/dashboard/tenant/residences/$id'
      preLoaderRoute: typeof DashboardTenantsectionsResidencesIdRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/tenant/(sections)/favourites/$id': {
      id: '/dashboard/tenant/(sections)/favourites/$id'
      path: '/favourites/$id'
      fullPath: '/dashboard/tenant/favourites/$id'
      preLoaderRoute: typeof DashboardTenantsectionsFavouritesIdRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/tenant/(sections)/applications/$id': {
      id: '/dashboard/tenant/(sections)/applications/$id'
      path: '/applications/$id'
      fullPath: '/dashboard/tenant/applications/$id'
      preLoaderRoute: typeof DashboardTenantsectionsApplicationsIdRouteImport
      parentRoute: typeof DashboardTenantLayoutRoute
    }
    '/dashboard/manager/(sections)/managed-properties/$id': {
      id: '/dashboard/manager/(sections)/managed-properties/$id'
      path: '/managed-properties/$id'
      fullPath: '/dashboard/manager/managed-properties/$id'
      preLoaderRoute: typeof DashboardManagersectionsManagedPropertiesIdRouteImport
      parentRoute: typeof DashboardManagerLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLoginManagerRoute: typeof authLoginManagerRoute
  authLoginTenantRoute: typeof authLoginTenantRoute
  authRegisterManagerRoute: typeof authRegisterManagerRoute
  authRegisterTenantRoute: typeof authRegisterTenantRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLoginManagerRoute: authLoginManagerRoute,
  authLoginTenantRoute: authLoginTenantRoute,
  authRegisterManagerRoute: authRegisterManagerRoute,
  authRegisterTenantRoute: authRegisterTenantRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface nondashboardLayoutRouteChildren {
  nondashboardLandingRoute: typeof nondashboardLandingRoute
  nondashboardMapRoute: typeof nondashboardMapRoute
}

const nondashboardLayoutRouteChildren: nondashboardLayoutRouteChildren = {
  nondashboardLandingRoute: nondashboardLandingRoute,
  nondashboardMapRoute: nondashboardMapRoute,
}

const nondashboardLayoutRouteWithChildren =
  nondashboardLayoutRoute._addFileChildren(nondashboardLayoutRouteChildren)

interface DashboardManagerLayoutRouteChildren {
  DashboardManagersectionsCreatePropertyRoute: typeof DashboardManagersectionsCreatePropertyRoute
  DashboardManagersectionsPageRoute: typeof DashboardManagersectionsPageRoute
  DashboardManagersectionsManagedPropertiesIdRoute: typeof DashboardManagersectionsManagedPropertiesIdRoute
  DashboardManagersectionsManagedPropertiesPageRoute: typeof DashboardManagersectionsManagedPropertiesPageRoute
}

const DashboardManagerLayoutRouteChildren: DashboardManagerLayoutRouteChildren =
  {
    DashboardManagersectionsCreatePropertyRoute:
      DashboardManagersectionsCreatePropertyRoute,
    DashboardManagersectionsPageRoute: DashboardManagersectionsPageRoute,
    DashboardManagersectionsManagedPropertiesIdRoute:
      DashboardManagersectionsManagedPropertiesIdRoute,
    DashboardManagersectionsManagedPropertiesPageRoute:
      DashboardManagersectionsManagedPropertiesPageRoute,
  }

const DashboardManagerLayoutRouteWithChildren =
  DashboardManagerLayoutRoute._addFileChildren(
    DashboardManagerLayoutRouteChildren,
  )

interface DashboardTenantLayoutRouteChildren {
  DashboardTenantsectionsSettingsRoute: typeof DashboardTenantsectionsSettingsRoute
  DashboardTenantsectionsPageRoute: typeof DashboardTenantsectionsPageRoute
  DashboardTenantsectionsApplicationsIdRoute: typeof DashboardTenantsectionsApplicationsIdRoute
  DashboardTenantsectionsFavouritesIdRoute: typeof DashboardTenantsectionsFavouritesIdRoute
  DashboardTenantsectionsResidencesIdRoute: typeof DashboardTenantsectionsResidencesIdRoute
  DashboardTenantsectionsApplicationsPageRoute: typeof DashboardTenantsectionsApplicationsPageRoute
  DashboardTenantsectionsFavouritesPageRoute: typeof DashboardTenantsectionsFavouritesPageRoute
  DashboardTenantsectionsResidencesPageRoute: typeof DashboardTenantsectionsResidencesPageRoute
}

const DashboardTenantLayoutRouteChildren: DashboardTenantLayoutRouteChildren = {
  DashboardTenantsectionsSettingsRoute: DashboardTenantsectionsSettingsRoute,
  DashboardTenantsectionsPageRoute: DashboardTenantsectionsPageRoute,
  DashboardTenantsectionsApplicationsIdRoute:
    DashboardTenantsectionsApplicationsIdRoute,
  DashboardTenantsectionsFavouritesIdRoute:
    DashboardTenantsectionsFavouritesIdRoute,
  DashboardTenantsectionsResidencesIdRoute:
    DashboardTenantsectionsResidencesIdRoute,
  DashboardTenantsectionsApplicationsPageRoute:
    DashboardTenantsectionsApplicationsPageRoute,
  DashboardTenantsectionsFavouritesPageRoute:
    DashboardTenantsectionsFavouritesPageRoute,
  DashboardTenantsectionsResidencesPageRoute:
    DashboardTenantsectionsResidencesPageRoute,
}

const DashboardTenantLayoutRouteWithChildren =
  DashboardTenantLayoutRoute._addFileChildren(
    DashboardTenantLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardManagerLayoutRoute: typeof DashboardManagerLayoutRouteWithChildren
  DashboardTenantLayoutRoute: typeof DashboardTenantLayoutRouteWithChildren
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardManagerLayoutRoute: DashboardManagerLayoutRouteWithChildren,
  DashboardTenantLayoutRoute: DashboardTenantLayoutRouteWithChildren,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  nondashboardLayoutRoute: nondashboardLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
