/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AboutRouteImport } from './app/about'
import { Route as nondashboardLayoutRouteImport } from './app/(nondashboard)/layout'
import { Route as authLayoutRouteImport } from './app/(auth)/layout'
import { Route as PageRouteImport } from './app/page'
import { Route as nondashboardLandingPageRouteImport } from './app/(nondashboard)/landing/page'
import { Route as authRegisterPageRouteImport } from './app/(auth)/register/page'
import { Route as authLoginTenantPageRouteImport } from './app/(auth)/login/tenant/page'
import { Route as authLoginManagerPageRouteImport } from './app/(auth)/login/manager/page'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const nondashboardLayoutRoute = nondashboardLayoutRouteImport.update({
  id: '/(nondashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const nondashboardLandingPageRoute = nondashboardLandingPageRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => nondashboardLayoutRoute,
} as any)
const authRegisterPageRoute = authRegisterPageRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginTenantPageRoute = authLoginTenantPageRouteImport.update({
  id: '/login/tenant/',
  path: '/login/tenant/',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginManagerPageRoute = authLoginManagerPageRouteImport.update({
  id: '/login/manager/',
  path: '/login/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof nondashboardLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof authRegisterPageRoute
  '/landing': typeof nondashboardLandingPageRoute
  '/login/manager': typeof authLoginManagerPageRoute
  '/login/tenant': typeof authLoginTenantPageRoute
}
export interface FileRoutesByTo {
  '/': typeof nondashboardLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof authRegisterPageRoute
  '/landing': typeof nondashboardLandingPageRoute
  '/login/manager': typeof authLoginManagerPageRoute
  '/login/tenant': typeof authLoginTenantPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(nondashboard)': typeof nondashboardLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/(auth)/register/': typeof authRegisterPageRoute
  '/(nondashboard)/landing/': typeof nondashboardLandingPageRoute
  '/(auth)/login/manager/': typeof authLoginManagerPageRoute
  '/(auth)/login/tenant/': typeof authLoginTenantPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/register'
    | '/landing'
    | '/login/manager'
    | '/login/tenant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register'
    | '/landing'
    | '/login/manager'
    | '/login/tenant'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(nondashboard)'
    | '/about'
    | '/(auth)/register/'
    | '/(nondashboard)/landing/'
    | '/(auth)/login/manager/'
    | '/(auth)/login/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  nondashboardLayoutRoute: typeof nondashboardLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nondashboard)': {
      id: '/(nondashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof nondashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nondashboard)/landing/': {
      id: '/(nondashboard)/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof nondashboardLandingPageRouteImport
      parentRoute: typeof nondashboardLayoutRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterPageRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login/tenant/': {
      id: '/(auth)/login/tenant/'
      path: '/login/tenant'
      fullPath: '/login/tenant'
      preLoaderRoute: typeof authLoginTenantPageRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login/manager/': {
      id: '/(auth)/login/manager/'
      path: '/login/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof authLoginManagerPageRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authRegisterPageRoute: typeof authRegisterPageRoute
  authLoginManagerPageRoute: typeof authLoginManagerPageRoute
  authLoginTenantPageRoute: typeof authLoginTenantPageRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authRegisterPageRoute: authRegisterPageRoute,
  authLoginManagerPageRoute: authLoginManagerPageRoute,
  authLoginTenantPageRoute: authLoginTenantPageRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface nondashboardLayoutRouteChildren {
  nondashboardLandingPageRoute: typeof nondashboardLandingPageRoute
}

const nondashboardLayoutRouteChildren: nondashboardLayoutRouteChildren = {
  nondashboardLandingPageRoute: nondashboardLandingPageRoute,
}

const nondashboardLayoutRouteWithChildren =
  nondashboardLayoutRoute._addFileChildren(nondashboardLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  nondashboardLayoutRoute: nondashboardLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
